Configuratron:
  use_only:
    - mmidb
  preload: True
  sfreq: 256
  deep1010:
    return_mask: False

encoder_weights: checkpoints/encoder_baseline.pt
context_weights: checkpoints/contextualizer_baseline.pt

datasets: !include configs/downstream_datasets.yml

